---
title: "Ploty"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r message = FALSE, echo = FALSE}
library(tidyverse)
library(plotly)
```



# Hospitalization rates across PUMAs, colored by borough
```{r}
puma_level_data %>% 
  mutate(puma = fct_reorder(puma, covid_vax_rate)) %>% 
  plot_ly(y = ~covid_hosp_rate, 
          x = ~puma, 
          color = ~borough, 
          type = "scatter") %>% 
  layout(title = "Hospitalization rates across PUMAs",
         xaxis = list(title = "PUMA",
                      zerolinecolor = '#ffff',
                      gridcolor = 'ffff'),
         yaxis = list(title = "% Hospitalized",
                      zerolinecolor = '#ffff',
                      gridcolor = 'ffff'),
         legend = list(title = list(text = 'Borough')))
```


# Death rates across PUMAs, colored by borough
```{r}
puma_level_data %>% 
  mutate(puma = fct_reorder(puma, covid_death_rate)) %>% 
  plot_ly(y = ~covid_death_rate, 
          x = ~puma, 
          color = ~borough, 
          type = "scatter") %>% 
  layout(title = "Death rates across PUMAs",
         xaxis = list(title = "PUMA",
                      zerolinecolor = '#ffff',
                      gridcolor = 'ffff'),
         yaxis = list(title = "% Death",
                      zerolinecolor = '#ffff',
                      gridcolor = 'ffff'),
         legend = list(title = list(text = 'Borough')))
```


# Vax rates across PUMAs, colored by borough
```{r}
puma_level_data %>% 
  mutate(puma = fct_reorder(puma, covid_vax_rate)) %>%
  plot_ly(y = ~covid_vax_rate, 
          x = ~puma, 
          color = ~borough, 
          type = "scatter") %>% 
  layout(title = "Vaccination rates across PUMAs",
         xaxis = list(title = "PUMA",
                      zerolinecolor = '#ffff',
                      gridcolor = 'ffff'),
         yaxis = list(title = "% Vaccinated",
                      zerolinecolor = '#ffff',
                      gridcolor = 'ffff'),
         legend = list(title = list(text = 'Borough')))
```



